Content-Type: multipart/mixed; boundary="boundary"
Date: Tue, 12 Dec 2023 23:30:44 +0700
MIME-Version: 1.0
To: ronaldo@fit.hcmus.edu.vn, hello@gmail.com
Cc: 
From: Khanh Hoang <idontknow@fit.hcmus.edu.vn>
Subject: Xin chao

This is a multi-part message in MIME format.
--boundary
Content-Type: text/plain; charset=UTF-8; format=flowed

Hello Bonjour Bella Ciao ahihi

--boundary
Content-Type: text/plain; charset=UTF-8; name="Test.txt"
Content-Disposition: attachment; filename="Test.txt"
Content-Transfer-Encoding: base64

SGVsbG8NCkkgYW0gYSB0ZXh0IGZpbGUuDQpCeWU=

--boundary--
