Message-ID: <7cd56c1d-f060-4f9a-a48f-b33b30f04f67@gmail.com>
Date: Sat, 16 Dec 2023 22:27:59 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: hello@gmail.com
Cc: ronaldo@fit.hcmus.edu.vn
From: Khanh Hoang <host@gmail.com>
Subject: La Lung em hoi
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Hay toi ben anh trong chieu dong xa vang

Ma sao gio day nhin lai chang con thay em

